name: Bug report
description: Create a report where you describe the type of bug
title: "<title>"

- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **Mod version**: 1.0.0
        - **Forge version**: 1.18.1 - 39.0.75
        - **Minecraft version**: 1.18.1
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: true